bash scripts/ablation-algorithm/run.sh
bash scripts/ablation-mem-breakdown/run.sh
bash scripts/ablation-segment/run.sh
bash scripts/ablation-time-breakdown/run.sh
bash scripts/end2end-memory/run.sh
bash scripts/end2end-time/run-a800.sh
bash scripts/extension-2d/run.sh
bash scripts/extension-offload/run.sh
bash scripts/ablation-predictor/run.sh
